#ifndef SFML_CONSTANTS_H
#define SFML_CONSTANTS_H

const float SCREEN_WIDTH = 1200;
const float SCREEN_HEIGHT = 750;
const float WORK_PANEL = SCREEN_WIDTH-450;
const float SIDE_BAR = SCREEN_WIDTH-750;


const int SB_MOUSE_POSITION = 0;
const int SB_MOUSE_CLICKED = SB_MOUSE_POSITION + 31;
const int SB_KEY_PRESSED = SB_MOUSE_POSITION + 30;
const int SB_DOMAIN = SB_MOUSE_POSITION + 2;
const int SB_EQUATION = SB_MOUSE_POSITION + 5;





#endif // SFML_CONSTANTS_H
